
const registerUser = async (req,res,next) => {
    try {
        
    } catch (error) {
        
    }
}